/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NonAuthLayoutImport } from './routes/_non-auth-layout'

// Create Virtual Routes

const LoginIndexLazyImport = createFileRoute('/login/')()
const NonAuthLayoutIndexLazyImport = createFileRoute('/_non-auth-layout/')()
const NonAuthLayoutUsersIndexLazyImport = createFileRoute(
  '/_non-auth-layout/users/',
)()
const NonAuthLayoutUsageTrackingIndexLazyImport = createFileRoute(
  '/_non-auth-layout/usage-tracking/',
)()
const NonAuthLayoutStaffsIndexLazyImport = createFileRoute(
  '/_non-auth-layout/staffs/',
)()
const NonAuthLayoutServicesIndexLazyImport = createFileRoute(
  '/_non-auth-layout/services/',
)()
const NonAuthLayoutServiceCategoriesIndexLazyImport = createFileRoute(
  '/_non-auth-layout/service-categories/',
)()
const NonAuthLayoutProvidersIndexLazyImport = createFileRoute(
  '/_non-auth-layout/providers/',
)()
const NonAuthLayoutPositionsIndexLazyImport = createFileRoute(
  '/_non-auth-layout/positions/',
)()
const NonAuthLayoutPeripheralsIndexLazyImport = createFileRoute(
  '/_non-auth-layout/peripherals/',
)()
const NonAuthLayoutGuestsIndexLazyImport = createFileRoute(
  '/_non-auth-layout/guests/',
)()
const NonAuthLayoutComputersIndexLazyImport = createFileRoute(
  '/_non-auth-layout/computers/',
)()
const NonAuthLayoutBranchesIndexLazyImport = createFileRoute(
  '/_non-auth-layout/branches/',
)()
const NonAuthLayoutBillsIndexLazyImport = createFileRoute(
  '/_non-auth-layout/bills/',
)()
const NonAuthLayoutUsersDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/users/deleted/',
)()
const NonAuthLayoutUsageTrackingDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/usage-tracking/deleted/',
)()
const NonAuthLayoutStaffsDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/staffs/deleted/',
)()
const NonAuthLayoutServicesDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/services/deleted/',
)()
const NonAuthLayoutServiceCategoriesDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/service-categories/deleted/',
)()
const NonAuthLayoutProvidersDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/providers/deleted/',
)()
const NonAuthLayoutPositionsDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/positions/deleted/',
)()
const NonAuthLayoutPeripheralsDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/peripherals/deleted/',
)()
const NonAuthLayoutGuestsLoginComputerIndexLazyImport = createFileRoute(
  '/_non-auth-layout/guests/login-computer/',
)()
const NonAuthLayoutGuestsDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/guests/deleted/',
)()
const NonAuthLayoutGuestsBranchesIndexLazyImport = createFileRoute(
  '/_non-auth-layout/guests/branches/',
)()
const NonAuthLayoutComputersDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/computers/deleted/',
)()
const NonAuthLayoutBranchesDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/branches/deleted/',
)()
const NonAuthLayoutBillsDeletedIndexLazyImport = createFileRoute(
  '/_non-auth-layout/bills/deleted/',
)()
const NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyImport =
  createFileRoute(
    '/_non-auth-layout/guests/login-computer/position/$positionId/',
  )()
const NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyImport =
  createFileRoute('/_non-auth-layout/guests/branches/$branchId/computers/')()

// Create/Update Routes

const NonAuthLayoutRoute = NonAuthLayoutImport.update({
  id: '/_non-auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const NonAuthLayoutIndexLazyRoute = NonAuthLayoutIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NonAuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_non-auth-layout/index.lazy').then((d) => d.Route),
)

const NonAuthLayoutUsersIndexLazyRoute =
  NonAuthLayoutUsersIndexLazyImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/users/index.lazy').then((d) => d.Route),
  )

const NonAuthLayoutUsageTrackingIndexLazyRoute =
  NonAuthLayoutUsageTrackingIndexLazyImport.update({
    id: '/usage-tracking/',
    path: '/usage-tracking/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/usage-tracking/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutStaffsIndexLazyRoute =
  NonAuthLayoutStaffsIndexLazyImport.update({
    id: '/staffs/',
    path: '/staffs/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/staffs/index.lazy').then((d) => d.Route),
  )

const NonAuthLayoutServicesIndexLazyRoute =
  NonAuthLayoutServicesIndexLazyImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/services/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutServiceCategoriesIndexLazyRoute =
  NonAuthLayoutServiceCategoriesIndexLazyImport.update({
    id: '/service-categories/',
    path: '/service-categories/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/service-categories/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutProvidersIndexLazyRoute =
  NonAuthLayoutProvidersIndexLazyImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/providers/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutPositionsIndexLazyRoute =
  NonAuthLayoutPositionsIndexLazyImport.update({
    id: '/positions/',
    path: '/positions/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/positions/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutPeripheralsIndexLazyRoute =
  NonAuthLayoutPeripheralsIndexLazyImport.update({
    id: '/peripherals/',
    path: '/peripherals/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/peripherals/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutGuestsIndexLazyRoute =
  NonAuthLayoutGuestsIndexLazyImport.update({
    id: '/guests/',
    path: '/guests/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/guests/index.lazy').then((d) => d.Route),
  )

const NonAuthLayoutComputersIndexLazyRoute =
  NonAuthLayoutComputersIndexLazyImport.update({
    id: '/computers/',
    path: '/computers/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/computers/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutBranchesIndexLazyRoute =
  NonAuthLayoutBranchesIndexLazyImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/branches/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutBillsIndexLazyRoute =
  NonAuthLayoutBillsIndexLazyImport.update({
    id: '/bills/',
    path: '/bills/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/bills/index.lazy').then((d) => d.Route),
  )

const NonAuthLayoutUsersDeletedIndexLazyRoute =
  NonAuthLayoutUsersDeletedIndexLazyImport.update({
    id: '/users/deleted/',
    path: '/users/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/users/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutUsageTrackingDeletedIndexLazyRoute =
  NonAuthLayoutUsageTrackingDeletedIndexLazyImport.update({
    id: '/usage-tracking/deleted/',
    path: '/usage-tracking/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/usage-tracking/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutStaffsDeletedIndexLazyRoute =
  NonAuthLayoutStaffsDeletedIndexLazyImport.update({
    id: '/staffs/deleted/',
    path: '/staffs/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/staffs/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutServicesDeletedIndexLazyRoute =
  NonAuthLayoutServicesDeletedIndexLazyImport.update({
    id: '/services/deleted/',
    path: '/services/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/services/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutServiceCategoriesDeletedIndexLazyRoute =
  NonAuthLayoutServiceCategoriesDeletedIndexLazyImport.update({
    id: '/service-categories/deleted/',
    path: '/service-categories/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import(
      './routes/_non-auth-layout/service-categories/deleted/index.lazy'
    ).then((d) => d.Route),
  )

const NonAuthLayoutProvidersDeletedIndexLazyRoute =
  NonAuthLayoutProvidersDeletedIndexLazyImport.update({
    id: '/providers/deleted/',
    path: '/providers/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/providers/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutPositionsDeletedIndexLazyRoute =
  NonAuthLayoutPositionsDeletedIndexLazyImport.update({
    id: '/positions/deleted/',
    path: '/positions/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/positions/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutPeripheralsDeletedIndexLazyRoute =
  NonAuthLayoutPeripheralsDeletedIndexLazyImport.update({
    id: '/peripherals/deleted/',
    path: '/peripherals/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/peripherals/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutGuestsLoginComputerIndexLazyRoute =
  NonAuthLayoutGuestsLoginComputerIndexLazyImport.update({
    id: '/guests/login-computer/',
    path: '/guests/login-computer/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/guests/login-computer/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutGuestsDeletedIndexLazyRoute =
  NonAuthLayoutGuestsDeletedIndexLazyImport.update({
    id: '/guests/deleted/',
    path: '/guests/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/guests/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutGuestsBranchesIndexLazyRoute =
  NonAuthLayoutGuestsBranchesIndexLazyImport.update({
    id: '/guests/branches/',
    path: '/guests/branches/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/guests/branches/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutComputersDeletedIndexLazyRoute =
  NonAuthLayoutComputersDeletedIndexLazyImport.update({
    id: '/computers/deleted/',
    path: '/computers/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/computers/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutBranchesDeletedIndexLazyRoute =
  NonAuthLayoutBranchesDeletedIndexLazyImport.update({
    id: '/branches/deleted/',
    path: '/branches/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/branches/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutBillsDeletedIndexLazyRoute =
  NonAuthLayoutBillsDeletedIndexLazyImport.update({
    id: '/bills/deleted/',
    path: '/bills/deleted/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_non-auth-layout/bills/deleted/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyRoute =
  NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyImport.update({
    id: '/guests/login-computer/position/$positionId/',
    path: '/guests/login-computer/position/$positionId/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import(
      './routes/_non-auth-layout/guests/login-computer/position/$positionId/index.lazy'
    ).then((d) => d.Route),
  )

const NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyRoute =
  NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyImport.update({
    id: '/guests/branches/$branchId/computers/',
    path: '/guests/branches/$branchId/computers/',
    getParentRoute: () => NonAuthLayoutRoute,
  } as any).lazy(() =>
    import(
      './routes/_non-auth-layout/guests/branches/$branchId/computers/index.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_non-auth-layout': {
      id: '/_non-auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NonAuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_non-auth-layout/': {
      id: '/_non-auth-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NonAuthLayoutIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_non-auth-layout/bills/': {
      id: '/_non-auth-layout/bills/'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof NonAuthLayoutBillsIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/branches/': {
      id: '/_non-auth-layout/branches/'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof NonAuthLayoutBranchesIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/computers/': {
      id: '/_non-auth-layout/computers/'
      path: '/computers'
      fullPath: '/computers'
      preLoaderRoute: typeof NonAuthLayoutComputersIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/guests/': {
      id: '/_non-auth-layout/guests/'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof NonAuthLayoutGuestsIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/peripherals/': {
      id: '/_non-auth-layout/peripherals/'
      path: '/peripherals'
      fullPath: '/peripherals'
      preLoaderRoute: typeof NonAuthLayoutPeripheralsIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/positions/': {
      id: '/_non-auth-layout/positions/'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof NonAuthLayoutPositionsIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/providers/': {
      id: '/_non-auth-layout/providers/'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof NonAuthLayoutProvidersIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/service-categories/': {
      id: '/_non-auth-layout/service-categories/'
      path: '/service-categories'
      fullPath: '/service-categories'
      preLoaderRoute: typeof NonAuthLayoutServiceCategoriesIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/services/': {
      id: '/_non-auth-layout/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof NonAuthLayoutServicesIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/staffs/': {
      id: '/_non-auth-layout/staffs/'
      path: '/staffs'
      fullPath: '/staffs'
      preLoaderRoute: typeof NonAuthLayoutStaffsIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/usage-tracking/': {
      id: '/_non-auth-layout/usage-tracking/'
      path: '/usage-tracking'
      fullPath: '/usage-tracking'
      preLoaderRoute: typeof NonAuthLayoutUsageTrackingIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/users/': {
      id: '/_non-auth-layout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof NonAuthLayoutUsersIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/bills/deleted/': {
      id: '/_non-auth-layout/bills/deleted/'
      path: '/bills/deleted'
      fullPath: '/bills/deleted'
      preLoaderRoute: typeof NonAuthLayoutBillsDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/branches/deleted/': {
      id: '/_non-auth-layout/branches/deleted/'
      path: '/branches/deleted'
      fullPath: '/branches/deleted'
      preLoaderRoute: typeof NonAuthLayoutBranchesDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/computers/deleted/': {
      id: '/_non-auth-layout/computers/deleted/'
      path: '/computers/deleted'
      fullPath: '/computers/deleted'
      preLoaderRoute: typeof NonAuthLayoutComputersDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/guests/branches/': {
      id: '/_non-auth-layout/guests/branches/'
      path: '/guests/branches'
      fullPath: '/guests/branches'
      preLoaderRoute: typeof NonAuthLayoutGuestsBranchesIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/guests/deleted/': {
      id: '/_non-auth-layout/guests/deleted/'
      path: '/guests/deleted'
      fullPath: '/guests/deleted'
      preLoaderRoute: typeof NonAuthLayoutGuestsDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/guests/login-computer/': {
      id: '/_non-auth-layout/guests/login-computer/'
      path: '/guests/login-computer'
      fullPath: '/guests/login-computer'
      preLoaderRoute: typeof NonAuthLayoutGuestsLoginComputerIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/peripherals/deleted/': {
      id: '/_non-auth-layout/peripherals/deleted/'
      path: '/peripherals/deleted'
      fullPath: '/peripherals/deleted'
      preLoaderRoute: typeof NonAuthLayoutPeripheralsDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/positions/deleted/': {
      id: '/_non-auth-layout/positions/deleted/'
      path: '/positions/deleted'
      fullPath: '/positions/deleted'
      preLoaderRoute: typeof NonAuthLayoutPositionsDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/providers/deleted/': {
      id: '/_non-auth-layout/providers/deleted/'
      path: '/providers/deleted'
      fullPath: '/providers/deleted'
      preLoaderRoute: typeof NonAuthLayoutProvidersDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/service-categories/deleted/': {
      id: '/_non-auth-layout/service-categories/deleted/'
      path: '/service-categories/deleted'
      fullPath: '/service-categories/deleted'
      preLoaderRoute: typeof NonAuthLayoutServiceCategoriesDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/services/deleted/': {
      id: '/_non-auth-layout/services/deleted/'
      path: '/services/deleted'
      fullPath: '/services/deleted'
      preLoaderRoute: typeof NonAuthLayoutServicesDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/staffs/deleted/': {
      id: '/_non-auth-layout/staffs/deleted/'
      path: '/staffs/deleted'
      fullPath: '/staffs/deleted'
      preLoaderRoute: typeof NonAuthLayoutStaffsDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/usage-tracking/deleted/': {
      id: '/_non-auth-layout/usage-tracking/deleted/'
      path: '/usage-tracking/deleted'
      fullPath: '/usage-tracking/deleted'
      preLoaderRoute: typeof NonAuthLayoutUsageTrackingDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/users/deleted/': {
      id: '/_non-auth-layout/users/deleted/'
      path: '/users/deleted'
      fullPath: '/users/deleted'
      preLoaderRoute: typeof NonAuthLayoutUsersDeletedIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/guests/branches/$branchId/computers/': {
      id: '/_non-auth-layout/guests/branches/$branchId/computers/'
      path: '/guests/branches/$branchId/computers'
      fullPath: '/guests/branches/$branchId/computers'
      preLoaderRoute: typeof NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
    '/_non-auth-layout/guests/login-computer/position/$positionId/': {
      id: '/_non-auth-layout/guests/login-computer/position/$positionId/'
      path: '/guests/login-computer/position/$positionId'
      fullPath: '/guests/login-computer/position/$positionId'
      preLoaderRoute: typeof NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyImport
      parentRoute: typeof NonAuthLayoutImport
    }
  }
}

// Create and export the route tree

interface NonAuthLayoutRouteChildren {
  NonAuthLayoutIndexLazyRoute: typeof NonAuthLayoutIndexLazyRoute
  NonAuthLayoutBillsIndexLazyRoute: typeof NonAuthLayoutBillsIndexLazyRoute
  NonAuthLayoutBranchesIndexLazyRoute: typeof NonAuthLayoutBranchesIndexLazyRoute
  NonAuthLayoutComputersIndexLazyRoute: typeof NonAuthLayoutComputersIndexLazyRoute
  NonAuthLayoutGuestsIndexLazyRoute: typeof NonAuthLayoutGuestsIndexLazyRoute
  NonAuthLayoutPeripheralsIndexLazyRoute: typeof NonAuthLayoutPeripheralsIndexLazyRoute
  NonAuthLayoutPositionsIndexLazyRoute: typeof NonAuthLayoutPositionsIndexLazyRoute
  NonAuthLayoutProvidersIndexLazyRoute: typeof NonAuthLayoutProvidersIndexLazyRoute
  NonAuthLayoutServiceCategoriesIndexLazyRoute: typeof NonAuthLayoutServiceCategoriesIndexLazyRoute
  NonAuthLayoutServicesIndexLazyRoute: typeof NonAuthLayoutServicesIndexLazyRoute
  NonAuthLayoutStaffsIndexLazyRoute: typeof NonAuthLayoutStaffsIndexLazyRoute
  NonAuthLayoutUsageTrackingIndexLazyRoute: typeof NonAuthLayoutUsageTrackingIndexLazyRoute
  NonAuthLayoutUsersIndexLazyRoute: typeof NonAuthLayoutUsersIndexLazyRoute
  NonAuthLayoutBillsDeletedIndexLazyRoute: typeof NonAuthLayoutBillsDeletedIndexLazyRoute
  NonAuthLayoutBranchesDeletedIndexLazyRoute: typeof NonAuthLayoutBranchesDeletedIndexLazyRoute
  NonAuthLayoutComputersDeletedIndexLazyRoute: typeof NonAuthLayoutComputersDeletedIndexLazyRoute
  NonAuthLayoutGuestsBranchesIndexLazyRoute: typeof NonAuthLayoutGuestsBranchesIndexLazyRoute
  NonAuthLayoutGuestsDeletedIndexLazyRoute: typeof NonAuthLayoutGuestsDeletedIndexLazyRoute
  NonAuthLayoutGuestsLoginComputerIndexLazyRoute: typeof NonAuthLayoutGuestsLoginComputerIndexLazyRoute
  NonAuthLayoutPeripheralsDeletedIndexLazyRoute: typeof NonAuthLayoutPeripheralsDeletedIndexLazyRoute
  NonAuthLayoutPositionsDeletedIndexLazyRoute: typeof NonAuthLayoutPositionsDeletedIndexLazyRoute
  NonAuthLayoutProvidersDeletedIndexLazyRoute: typeof NonAuthLayoutProvidersDeletedIndexLazyRoute
  NonAuthLayoutServiceCategoriesDeletedIndexLazyRoute: typeof NonAuthLayoutServiceCategoriesDeletedIndexLazyRoute
  NonAuthLayoutServicesDeletedIndexLazyRoute: typeof NonAuthLayoutServicesDeletedIndexLazyRoute
  NonAuthLayoutStaffsDeletedIndexLazyRoute: typeof NonAuthLayoutStaffsDeletedIndexLazyRoute
  NonAuthLayoutUsageTrackingDeletedIndexLazyRoute: typeof NonAuthLayoutUsageTrackingDeletedIndexLazyRoute
  NonAuthLayoutUsersDeletedIndexLazyRoute: typeof NonAuthLayoutUsersDeletedIndexLazyRoute
  NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyRoute: typeof NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyRoute
  NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyRoute: typeof NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyRoute
}

const NonAuthLayoutRouteChildren: NonAuthLayoutRouteChildren = {
  NonAuthLayoutIndexLazyRoute: NonAuthLayoutIndexLazyRoute,
  NonAuthLayoutBillsIndexLazyRoute: NonAuthLayoutBillsIndexLazyRoute,
  NonAuthLayoutBranchesIndexLazyRoute: NonAuthLayoutBranchesIndexLazyRoute,
  NonAuthLayoutComputersIndexLazyRoute: NonAuthLayoutComputersIndexLazyRoute,
  NonAuthLayoutGuestsIndexLazyRoute: NonAuthLayoutGuestsIndexLazyRoute,
  NonAuthLayoutPeripheralsIndexLazyRoute:
    NonAuthLayoutPeripheralsIndexLazyRoute,
  NonAuthLayoutPositionsIndexLazyRoute: NonAuthLayoutPositionsIndexLazyRoute,
  NonAuthLayoutProvidersIndexLazyRoute: NonAuthLayoutProvidersIndexLazyRoute,
  NonAuthLayoutServiceCategoriesIndexLazyRoute:
    NonAuthLayoutServiceCategoriesIndexLazyRoute,
  NonAuthLayoutServicesIndexLazyRoute: NonAuthLayoutServicesIndexLazyRoute,
  NonAuthLayoutStaffsIndexLazyRoute: NonAuthLayoutStaffsIndexLazyRoute,
  NonAuthLayoutUsageTrackingIndexLazyRoute:
    NonAuthLayoutUsageTrackingIndexLazyRoute,
  NonAuthLayoutUsersIndexLazyRoute: NonAuthLayoutUsersIndexLazyRoute,
  NonAuthLayoutBillsDeletedIndexLazyRoute:
    NonAuthLayoutBillsDeletedIndexLazyRoute,
  NonAuthLayoutBranchesDeletedIndexLazyRoute:
    NonAuthLayoutBranchesDeletedIndexLazyRoute,
  NonAuthLayoutComputersDeletedIndexLazyRoute:
    NonAuthLayoutComputersDeletedIndexLazyRoute,
  NonAuthLayoutGuestsBranchesIndexLazyRoute:
    NonAuthLayoutGuestsBranchesIndexLazyRoute,
  NonAuthLayoutGuestsDeletedIndexLazyRoute:
    NonAuthLayoutGuestsDeletedIndexLazyRoute,
  NonAuthLayoutGuestsLoginComputerIndexLazyRoute:
    NonAuthLayoutGuestsLoginComputerIndexLazyRoute,
  NonAuthLayoutPeripheralsDeletedIndexLazyRoute:
    NonAuthLayoutPeripheralsDeletedIndexLazyRoute,
  NonAuthLayoutPositionsDeletedIndexLazyRoute:
    NonAuthLayoutPositionsDeletedIndexLazyRoute,
  NonAuthLayoutProvidersDeletedIndexLazyRoute:
    NonAuthLayoutProvidersDeletedIndexLazyRoute,
  NonAuthLayoutServiceCategoriesDeletedIndexLazyRoute:
    NonAuthLayoutServiceCategoriesDeletedIndexLazyRoute,
  NonAuthLayoutServicesDeletedIndexLazyRoute:
    NonAuthLayoutServicesDeletedIndexLazyRoute,
  NonAuthLayoutStaffsDeletedIndexLazyRoute:
    NonAuthLayoutStaffsDeletedIndexLazyRoute,
  NonAuthLayoutUsageTrackingDeletedIndexLazyRoute:
    NonAuthLayoutUsageTrackingDeletedIndexLazyRoute,
  NonAuthLayoutUsersDeletedIndexLazyRoute:
    NonAuthLayoutUsersDeletedIndexLazyRoute,
  NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyRoute:
    NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyRoute,
  NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyRoute:
    NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyRoute,
}

const NonAuthLayoutRouteWithChildren = NonAuthLayoutRoute._addFileChildren(
  NonAuthLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof NonAuthLayoutRouteWithChildren
  '/': typeof NonAuthLayoutIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/bills': typeof NonAuthLayoutBillsIndexLazyRoute
  '/branches': typeof NonAuthLayoutBranchesIndexLazyRoute
  '/computers': typeof NonAuthLayoutComputersIndexLazyRoute
  '/guests': typeof NonAuthLayoutGuestsIndexLazyRoute
  '/peripherals': typeof NonAuthLayoutPeripheralsIndexLazyRoute
  '/positions': typeof NonAuthLayoutPositionsIndexLazyRoute
  '/providers': typeof NonAuthLayoutProvidersIndexLazyRoute
  '/service-categories': typeof NonAuthLayoutServiceCategoriesIndexLazyRoute
  '/services': typeof NonAuthLayoutServicesIndexLazyRoute
  '/staffs': typeof NonAuthLayoutStaffsIndexLazyRoute
  '/usage-tracking': typeof NonAuthLayoutUsageTrackingIndexLazyRoute
  '/users': typeof NonAuthLayoutUsersIndexLazyRoute
  '/bills/deleted': typeof NonAuthLayoutBillsDeletedIndexLazyRoute
  '/branches/deleted': typeof NonAuthLayoutBranchesDeletedIndexLazyRoute
  '/computers/deleted': typeof NonAuthLayoutComputersDeletedIndexLazyRoute
  '/guests/branches': typeof NonAuthLayoutGuestsBranchesIndexLazyRoute
  '/guests/deleted': typeof NonAuthLayoutGuestsDeletedIndexLazyRoute
  '/guests/login-computer': typeof NonAuthLayoutGuestsLoginComputerIndexLazyRoute
  '/peripherals/deleted': typeof NonAuthLayoutPeripheralsDeletedIndexLazyRoute
  '/positions/deleted': typeof NonAuthLayoutPositionsDeletedIndexLazyRoute
  '/providers/deleted': typeof NonAuthLayoutProvidersDeletedIndexLazyRoute
  '/service-categories/deleted': typeof NonAuthLayoutServiceCategoriesDeletedIndexLazyRoute
  '/services/deleted': typeof NonAuthLayoutServicesDeletedIndexLazyRoute
  '/staffs/deleted': typeof NonAuthLayoutStaffsDeletedIndexLazyRoute
  '/usage-tracking/deleted': typeof NonAuthLayoutUsageTrackingDeletedIndexLazyRoute
  '/users/deleted': typeof NonAuthLayoutUsersDeletedIndexLazyRoute
  '/guests/branches/$branchId/computers': typeof NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyRoute
  '/guests/login-computer/position/$positionId': typeof NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof NonAuthLayoutIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/bills': typeof NonAuthLayoutBillsIndexLazyRoute
  '/branches': typeof NonAuthLayoutBranchesIndexLazyRoute
  '/computers': typeof NonAuthLayoutComputersIndexLazyRoute
  '/guests': typeof NonAuthLayoutGuestsIndexLazyRoute
  '/peripherals': typeof NonAuthLayoutPeripheralsIndexLazyRoute
  '/positions': typeof NonAuthLayoutPositionsIndexLazyRoute
  '/providers': typeof NonAuthLayoutProvidersIndexLazyRoute
  '/service-categories': typeof NonAuthLayoutServiceCategoriesIndexLazyRoute
  '/services': typeof NonAuthLayoutServicesIndexLazyRoute
  '/staffs': typeof NonAuthLayoutStaffsIndexLazyRoute
  '/usage-tracking': typeof NonAuthLayoutUsageTrackingIndexLazyRoute
  '/users': typeof NonAuthLayoutUsersIndexLazyRoute
  '/bills/deleted': typeof NonAuthLayoutBillsDeletedIndexLazyRoute
  '/branches/deleted': typeof NonAuthLayoutBranchesDeletedIndexLazyRoute
  '/computers/deleted': typeof NonAuthLayoutComputersDeletedIndexLazyRoute
  '/guests/branches': typeof NonAuthLayoutGuestsBranchesIndexLazyRoute
  '/guests/deleted': typeof NonAuthLayoutGuestsDeletedIndexLazyRoute
  '/guests/login-computer': typeof NonAuthLayoutGuestsLoginComputerIndexLazyRoute
  '/peripherals/deleted': typeof NonAuthLayoutPeripheralsDeletedIndexLazyRoute
  '/positions/deleted': typeof NonAuthLayoutPositionsDeletedIndexLazyRoute
  '/providers/deleted': typeof NonAuthLayoutProvidersDeletedIndexLazyRoute
  '/service-categories/deleted': typeof NonAuthLayoutServiceCategoriesDeletedIndexLazyRoute
  '/services/deleted': typeof NonAuthLayoutServicesDeletedIndexLazyRoute
  '/staffs/deleted': typeof NonAuthLayoutStaffsDeletedIndexLazyRoute
  '/usage-tracking/deleted': typeof NonAuthLayoutUsageTrackingDeletedIndexLazyRoute
  '/users/deleted': typeof NonAuthLayoutUsersDeletedIndexLazyRoute
  '/guests/branches/$branchId/computers': typeof NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyRoute
  '/guests/login-computer/position/$positionId': typeof NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_non-auth-layout': typeof NonAuthLayoutRouteWithChildren
  '/_non-auth-layout/': typeof NonAuthLayoutIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/_non-auth-layout/bills/': typeof NonAuthLayoutBillsIndexLazyRoute
  '/_non-auth-layout/branches/': typeof NonAuthLayoutBranchesIndexLazyRoute
  '/_non-auth-layout/computers/': typeof NonAuthLayoutComputersIndexLazyRoute
  '/_non-auth-layout/guests/': typeof NonAuthLayoutGuestsIndexLazyRoute
  '/_non-auth-layout/peripherals/': typeof NonAuthLayoutPeripheralsIndexLazyRoute
  '/_non-auth-layout/positions/': typeof NonAuthLayoutPositionsIndexLazyRoute
  '/_non-auth-layout/providers/': typeof NonAuthLayoutProvidersIndexLazyRoute
  '/_non-auth-layout/service-categories/': typeof NonAuthLayoutServiceCategoriesIndexLazyRoute
  '/_non-auth-layout/services/': typeof NonAuthLayoutServicesIndexLazyRoute
  '/_non-auth-layout/staffs/': typeof NonAuthLayoutStaffsIndexLazyRoute
  '/_non-auth-layout/usage-tracking/': typeof NonAuthLayoutUsageTrackingIndexLazyRoute
  '/_non-auth-layout/users/': typeof NonAuthLayoutUsersIndexLazyRoute
  '/_non-auth-layout/bills/deleted/': typeof NonAuthLayoutBillsDeletedIndexLazyRoute
  '/_non-auth-layout/branches/deleted/': typeof NonAuthLayoutBranchesDeletedIndexLazyRoute
  '/_non-auth-layout/computers/deleted/': typeof NonAuthLayoutComputersDeletedIndexLazyRoute
  '/_non-auth-layout/guests/branches/': typeof NonAuthLayoutGuestsBranchesIndexLazyRoute
  '/_non-auth-layout/guests/deleted/': typeof NonAuthLayoutGuestsDeletedIndexLazyRoute
  '/_non-auth-layout/guests/login-computer/': typeof NonAuthLayoutGuestsLoginComputerIndexLazyRoute
  '/_non-auth-layout/peripherals/deleted/': typeof NonAuthLayoutPeripheralsDeletedIndexLazyRoute
  '/_non-auth-layout/positions/deleted/': typeof NonAuthLayoutPositionsDeletedIndexLazyRoute
  '/_non-auth-layout/providers/deleted/': typeof NonAuthLayoutProvidersDeletedIndexLazyRoute
  '/_non-auth-layout/service-categories/deleted/': typeof NonAuthLayoutServiceCategoriesDeletedIndexLazyRoute
  '/_non-auth-layout/services/deleted/': typeof NonAuthLayoutServicesDeletedIndexLazyRoute
  '/_non-auth-layout/staffs/deleted/': typeof NonAuthLayoutStaffsDeletedIndexLazyRoute
  '/_non-auth-layout/usage-tracking/deleted/': typeof NonAuthLayoutUsageTrackingDeletedIndexLazyRoute
  '/_non-auth-layout/users/deleted/': typeof NonAuthLayoutUsersDeletedIndexLazyRoute
  '/_non-auth-layout/guests/branches/$branchId/computers/': typeof NonAuthLayoutGuestsBranchesBranchIdComputersIndexLazyRoute
  '/_non-auth-layout/guests/login-computer/position/$positionId/': typeof NonAuthLayoutGuestsLoginComputerPositionPositionIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/login'
    | '/bills'
    | '/branches'
    | '/computers'
    | '/guests'
    | '/peripherals'
    | '/positions'
    | '/providers'
    | '/service-categories'
    | '/services'
    | '/staffs'
    | '/usage-tracking'
    | '/users'
    | '/bills/deleted'
    | '/branches/deleted'
    | '/computers/deleted'
    | '/guests/branches'
    | '/guests/deleted'
    | '/guests/login-computer'
    | '/peripherals/deleted'
    | '/positions/deleted'
    | '/providers/deleted'
    | '/service-categories/deleted'
    | '/services/deleted'
    | '/staffs/deleted'
    | '/usage-tracking/deleted'
    | '/users/deleted'
    | '/guests/branches/$branchId/computers'
    | '/guests/login-computer/position/$positionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bills'
    | '/branches'
    | '/computers'
    | '/guests'
    | '/peripherals'
    | '/positions'
    | '/providers'
    | '/service-categories'
    | '/services'
    | '/staffs'
    | '/usage-tracking'
    | '/users'
    | '/bills/deleted'
    | '/branches/deleted'
    | '/computers/deleted'
    | '/guests/branches'
    | '/guests/deleted'
    | '/guests/login-computer'
    | '/peripherals/deleted'
    | '/positions/deleted'
    | '/providers/deleted'
    | '/service-categories/deleted'
    | '/services/deleted'
    | '/staffs/deleted'
    | '/usage-tracking/deleted'
    | '/users/deleted'
    | '/guests/branches/$branchId/computers'
    | '/guests/login-computer/position/$positionId'
  id:
    | '__root__'
    | '/_non-auth-layout'
    | '/_non-auth-layout/'
    | '/login/'
    | '/_non-auth-layout/bills/'
    | '/_non-auth-layout/branches/'
    | '/_non-auth-layout/computers/'
    | '/_non-auth-layout/guests/'
    | '/_non-auth-layout/peripherals/'
    | '/_non-auth-layout/positions/'
    | '/_non-auth-layout/providers/'
    | '/_non-auth-layout/service-categories/'
    | '/_non-auth-layout/services/'
    | '/_non-auth-layout/staffs/'
    | '/_non-auth-layout/usage-tracking/'
    | '/_non-auth-layout/users/'
    | '/_non-auth-layout/bills/deleted/'
    | '/_non-auth-layout/branches/deleted/'
    | '/_non-auth-layout/computers/deleted/'
    | '/_non-auth-layout/guests/branches/'
    | '/_non-auth-layout/guests/deleted/'
    | '/_non-auth-layout/guests/login-computer/'
    | '/_non-auth-layout/peripherals/deleted/'
    | '/_non-auth-layout/positions/deleted/'
    | '/_non-auth-layout/providers/deleted/'
    | '/_non-auth-layout/service-categories/deleted/'
    | '/_non-auth-layout/services/deleted/'
    | '/_non-auth-layout/staffs/deleted/'
    | '/_non-auth-layout/usage-tracking/deleted/'
    | '/_non-auth-layout/users/deleted/'
    | '/_non-auth-layout/guests/branches/$branchId/computers/'
    | '/_non-auth-layout/guests/login-computer/position/$positionId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NonAuthLayoutRoute: typeof NonAuthLayoutRouteWithChildren
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  NonAuthLayoutRoute: NonAuthLayoutRouteWithChildren,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_non-auth-layout",
        "/login/"
      ]
    },
    "/_non-auth-layout": {
      "filePath": "_non-auth-layout.tsx",
      "children": [
        "/_non-auth-layout/",
        "/_non-auth-layout/bills/",
        "/_non-auth-layout/branches/",
        "/_non-auth-layout/computers/",
        "/_non-auth-layout/guests/",
        "/_non-auth-layout/peripherals/",
        "/_non-auth-layout/positions/",
        "/_non-auth-layout/providers/",
        "/_non-auth-layout/service-categories/",
        "/_non-auth-layout/services/",
        "/_non-auth-layout/staffs/",
        "/_non-auth-layout/usage-tracking/",
        "/_non-auth-layout/users/",
        "/_non-auth-layout/bills/deleted/",
        "/_non-auth-layout/branches/deleted/",
        "/_non-auth-layout/computers/deleted/",
        "/_non-auth-layout/guests/branches/",
        "/_non-auth-layout/guests/deleted/",
        "/_non-auth-layout/guests/login-computer/",
        "/_non-auth-layout/peripherals/deleted/",
        "/_non-auth-layout/positions/deleted/",
        "/_non-auth-layout/providers/deleted/",
        "/_non-auth-layout/service-categories/deleted/",
        "/_non-auth-layout/services/deleted/",
        "/_non-auth-layout/staffs/deleted/",
        "/_non-auth-layout/usage-tracking/deleted/",
        "/_non-auth-layout/users/deleted/",
        "/_non-auth-layout/guests/branches/$branchId/computers/",
        "/_non-auth-layout/guests/login-computer/position/$positionId/"
      ]
    },
    "/_non-auth-layout/": {
      "filePath": "_non-auth-layout/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/_non-auth-layout/bills/": {
      "filePath": "_non-auth-layout/bills/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/branches/": {
      "filePath": "_non-auth-layout/branches/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/computers/": {
      "filePath": "_non-auth-layout/computers/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/guests/": {
      "filePath": "_non-auth-layout/guests/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/peripherals/": {
      "filePath": "_non-auth-layout/peripherals/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/positions/": {
      "filePath": "_non-auth-layout/positions/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/providers/": {
      "filePath": "_non-auth-layout/providers/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/service-categories/": {
      "filePath": "_non-auth-layout/service-categories/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/services/": {
      "filePath": "_non-auth-layout/services/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/staffs/": {
      "filePath": "_non-auth-layout/staffs/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/usage-tracking/": {
      "filePath": "_non-auth-layout/usage-tracking/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/users/": {
      "filePath": "_non-auth-layout/users/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/bills/deleted/": {
      "filePath": "_non-auth-layout/bills/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/branches/deleted/": {
      "filePath": "_non-auth-layout/branches/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/computers/deleted/": {
      "filePath": "_non-auth-layout/computers/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/guests/branches/": {
      "filePath": "_non-auth-layout/guests/branches/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/guests/deleted/": {
      "filePath": "_non-auth-layout/guests/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/guests/login-computer/": {
      "filePath": "_non-auth-layout/guests/login-computer/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/peripherals/deleted/": {
      "filePath": "_non-auth-layout/peripherals/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/positions/deleted/": {
      "filePath": "_non-auth-layout/positions/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/providers/deleted/": {
      "filePath": "_non-auth-layout/providers/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/service-categories/deleted/": {
      "filePath": "_non-auth-layout/service-categories/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/services/deleted/": {
      "filePath": "_non-auth-layout/services/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/staffs/deleted/": {
      "filePath": "_non-auth-layout/staffs/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/usage-tracking/deleted/": {
      "filePath": "_non-auth-layout/usage-tracking/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/users/deleted/": {
      "filePath": "_non-auth-layout/users/deleted/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/guests/branches/$branchId/computers/": {
      "filePath": "_non-auth-layout/guests/branches/$branchId/computers/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    },
    "/_non-auth-layout/guests/login-computer/position/$positionId/": {
      "filePath": "_non-auth-layout/guests/login-computer/position/$positionId/index.lazy.tsx",
      "parent": "/_non-auth-layout"
    }
  }
}
ROUTE_MANIFEST_END */
